[project]
id = "tatparya-local"
name = "Tatparya"

[api]
port = 54321
schemas = ["public"]

[db]
port = 54322

[auth]
site_url = "http://localhost:3000"
enable_signup = true

[auth.sms]
enable_signup = true
enable_confirmations = true

[auth.sms.twilio]
enabled = false
